### ISSUE TITLE
Social Connect 

### ISSUE THREAD

**Issue by Haz69** [mistic100/Piwigo-Social-Connect#10]
Hello/Hi/Greetings,

Hi I try to follow the instructions in the Social Connect config page, but can't get it to work for Google.

Can some one describe how to enable login with google in Social Connect?

I have followed the instructions in the plugin Social Connect, but when I come to Create Client ID ing Google API Manager and choose Web Application and fill all stuff , no save button appears?  Why ?

Do i have to pay get this working or what ?

Piwigo version: 2.8.2
PHP version: 5.6.26
MySQL version: 5.5.52
Piwigo URL: http://www.karlskogabilder.se

**Comment by mistic100** [comment]
Their web console entirely changed, again.

To manage the API credentials you must go to this page https://console.developers.google.com/apis/credentials

If you were on this page I can't tell you why you can't save, I just did it and it works.

**Comment by Haz69** [comment]
What are the requirements to get this working except a google account? Do you have to pay for seomthing extra to get it work such like a developer account or pay for a certain API?

I have tried that page 50 times therefore I Think something else basic is the reason, I am newbi to google API , howether the SOcial COnnect plugin works with twitter and facebook, but i cant get it to run with google

**Comment by mistic100** [comment]
I don't know. No it's a free API.

**Comment by Haz69** [comment]
This is what i have entered in the page Create client ID under credentials.

**Name**
**www.karlskogabilder.se**

**Authorized JavaScript origins**   
For use with requests from a browser. This is the origin URI of the client application. It can't contain a wildcard (http://*.example.com) or a path (http://example.com/subdir). If you're using a nonstandard port, you must include it in the origin URI. 

**http://www.karlskogabilder.se**

**Authorized redirect URIs**   
For use with requests from a web server. This is the path in your application that users are redirected to after they have authenticated with Google. The path will be appended with the authorization code for access. Must have a protocol. Cannot contain URL fragments or relative paths. Cannot be a public IP address
http://www.karlskogabilder.se/piwigo/plugins/oAuth/include/hybridauth/?hauth.done=Google

But the save button is not appearing only a grey box on the left of the cancel button.

**Comment by Haz69** [comment]
Exactly wich API are being used for this?

**Comment by Haz69** [comment]
I think your guide in the plug in needs to be updated....

**Comment by mistic100** [comment]
Done, almost nothing changes but the console URL, everything else is correct.

And I can't tell you why you can't save, try with another browser. It's not related to the plugin.

**Comment by Haz69** [comment]
Whats the name of the API to use?

**Comment by mistic100** [comment]
I don't know what you mean, you go to the "Credentials" tab and create new OAuth ID, it's not linked to any API.

**Comment by Haz69** [comment]
It works now, Browserrelated!
