### ISSUE TITLE
Facebook doesn't seem to work anymore

### ISSUE THREAD

**Issue by bernux** [mistic100/Piwigo-Social-Connect#14]
I Don't know if it's related to the EOL of their API version 2.2 but FB auth doesn't work anymore

**Comment by bernux** [comment]
I don't have FB account so hard to debug but here is what I observed
The FB Page detect when password are wrong.
When password is correct, I get an "Authentication canceled" from my piwigo gallery

**Comment by bernux** [comment]
Library error Code 5

**Comment by Chartman123** [comment]
The problem can be fixed this way: http://stackoverflow.com/questions/42994019/facebook-graph-api-not-work-from-2-2-to-2-3

**Comment by bernux** [comment]
thanks @Chartman123
it works
For those who wants to know, the modification has to be done in the file : 
%PIWIGO_DIR%/plugins/oAuth/include/hybridauth/Hybrid/thirdparty/Facebook/base_facebook.php

**Comment by Chartman123** [comment]
You're welcome. I think this change should be included into the plugin :)

**Comment by mistic100** [comment]
I can't update the whole Hybridauth lib (would need to test everything).
@bernux did you applied the changes manually or did you grab `base_facebook.php` from a newer version of Hybridauth ?

**Comment by bernux** [comment]
I applied the change manually

**Comment by mistic100** [comment]
Thank you very much, I published version 2.2.5, should be available on your galleries.

**Comment by Chartman123** [comment]
> I can't update the whole Hybridauth lib (would need to test everything).

I've tried that first, but it didn't work. ;) So thanks for the quick fix.
