### ISSUE TITLE
Google connection broken with piwigo 2.8.6

### ISSUE THREAD

**Issue by bernux** [mistic100/Piwigo-Social-Connect#15]
it's not the plug-in update which cause the trouble, I tried to downgrade to 2.2.4 and trouble still here so it's a problem with the 2.8.6 version of piwigo
I get Error code : 6, with all the google account
I don't know for the 2.9 version of piwigo ( not present in the FreeBSD ports for the moment )

**Comment by mistic100** [comment]
The Google Auth setup guide was updated in the previous version ("Help" button in the config page).
Can you check that everything is done correctly as per the new guide ?

**Comment by bernux** [comment]
OK Google+ API wasn't activated
But the real trouble was that I had my url ".../plugins/oAuth/include/hybridauth/?hauth.done=Google" configured 2 times (some trace from an old configuration) and the one in "URL de la page d'accueil (Facultatif)" was causing the fail

Thanks a lot
