### ISSUE TITLE
facebook oath is still broken

### ISSUE THREAD

**Issue by rananna** [mistic100/Piwigo-Social-Connect#16]
Facebook login is still not working

**Comment by mistic100** [comment]
Which error ? Which version ?
This is not how you make a big report.

**Comment by rananna** [comment]
my apologies - you are absolutely right!
Piwigo version # 2.9
social connect Latest revision date: 2017-04-21
error is shown in the attached file
Fac
![capture](https://cloud.githubusercontent.com/assets/28536098/25816431/16292d2a-33f2-11e7-89ff-3ef3ccf2c0c7.JPG)

**Comment by mistic100** [comment]
This is an error on facebook side I cannot debug it at all.

Are you sure your Facebook app is correctly configured ? The administration page changed again
Now after creating the app you need to click on "Add product", click "Start" in front of "Facebook Login" and fill the "Valid OAuth redirect URI" field with the URL provided by Social Connect.

**Comment by rananna** [comment]
Yes it was, the url was set incorrectly.

It is working now.

Thanks for looking into it.
