### ISSUE TITLE
Adding a new provider for Social Connect

### ISSUE THREAD

**Issue by oradio** [mistic100/Piwigo-Social-Connect#18]
Hi,

I want to add a new provider for Social Connect.

I downloaded the additional provider file from hybridauth, such as Weibo.php, and copied it to "\oAuth\include\hybridauth\Hybrid\Providers"

and edited providers_stats.inc.php, adding 

    'Weibo' => array(
    'name'              => 'Weibo',
    'require_client_id' => true,
    'new_app_link'      => null,
    'about_link'        => 'http://open.weibo.com',

Now I can see Weibo listed with other providers, but when I enable it, the Application Key and Application Secret fields do not show up.

So I guess there is something missing with my configurations, can you tell how many steps are there to add a new provider? 

Thank you!

Piwigo version: 2.9.2

**Comment by mistic100** [comment]
You need to provide "new_app_link", otherwise the config page asumes there is nothing to configure https://github.com/mistic100/Piwigo-Social-Connect/blob/master/admin/template/providers.tpl#L68

**Comment by oradio** [comment]
Thank you for the quick reply!

Now I can add the provider, but the url did not show up on the sign in page.

`<fieldset style="text-align:center;" id="oauth_wrap">
  <legend>Or sign in with</legend>
  
<a href="#" class="oauth oauth_16px weibo" data-idp="Weibo" title="Weibo"></a>
</fieldset>`

Is there some thing that I missed? 
thanks.

**Comment by mistic100** [comment]
Did you enabled it in the conf ? (and didn't forget to save ?)
If so I don't know.

**Comment by oradio** [comment]
Yes, I enabled and saved it in the plugin conf, and I checked the codes are like this: url is empty:

![social20171022191440](https://user-images.githubusercontent.com/2052700/31861292-4d4c179c-b75d-11e7-8c8a-07de7afa2be8.png)

**Comment by mistic100** [comment]
This is notmal but of course you need to add the image, how would it work otherwise ?

Add the icon (square) at the end of the row of the three sprites here https://github.com/mistic100/Piwigo-Social-Connect/tree/master/template/images

And add
```css
.oauth_16px.weibo { background-position: -224px 0px; }
.oauth_26px.weibo { background-position: -364px 0px; }
.oauth_38px.weibo { background-position: -532px 0px; }
```
in https://github.com/mistic100/Piwigo-Social-Connect/blob/master/template/oauth_sprites.css

**Comment by oradio** [comment]
Cool! It is working now 👍 
I will post this to the piwigo forum for people who have the same question.

Thank you for the great plugin! 💯
