### ISSUE TITLE
Transfer Social Connect

### ISSUE THREAD

**Issue by tkrn** [mistic100/Piwigo-Social-Connect#23]
Dear mistic100 - I've fixed an issue since your release. I would like to continue to maintain your project which youve created. If you wouldn't mind, please transfer me the repo and the extension page at https://piwigo.org/ext/extension_view.php?eid=684 and I'll be happy to keep your project going.

Thanks,
tkrn

**Comment by mistic100** [comment]
>  I've fixed an issue since your release

please submit a PR
