### ISSUE TITLE
[mysql error 1054] Unknown column 'oauth_id' in 'field list'

### ISSUE THREAD

**Issue by WilbertSmith** [mistic100/Piwigo-Social-Connect#5]
Fresh Piwigo 2.7.4 install. 
Environment:
        Operating system: Linux
        PHP: 5.5.23 (Show info) [2015-05-02 16:46:38]
        MySQL: 5.5.41-MariaDB [2015-05-02 16:46:38]
        Graphics Library: External ImageMagick 6.8.6-3

If Social Connect plugin is enabled it's not possible to manage users. 
Browser pop-up window: "DataTables warning (table id = 'userList'): DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error." 

Firebug console:

```
<b>Warning</b>:  [mysql error 1054] Unknown column 'oauth_id' in 'field list'

		SELECT SQL_CALC_FOUND_ROWS id, username, status, mail_address, recent_period, level, registration_date
, oauth_id
		FROM   piwigo_users INNER JOIN piwigo_user_infos AS ui ON id = ui.user_id
		
		ORDER BY  id
				 	asc
		LIMIT 0, 10
	 in <b>/data/pics/piwigo/include/dblayer/functions_mysqli.inc.php</b> on line <b>830</b><br />
</pre><br />
<b>Fatal error</b>:  Call to a member function fetch_array() on a non-object in <b>/data/pics/piwigo
/include/dblayer/functions_mysqli.inc.php</b> on line <b>206</b><br />
```

**Comment by mistic100** [comment]
Go to Plugins admin page and click "Restore" for this plugin, should re-run the install script

**Comment by WilbertSmith** [comment]
On 02.05.2015 17:03, Damien Sorel wrote:
>
> Go to Plugins admin page and click "Restore" for this plugin, should
> re-run the install script
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mistic100/Piwigo-Social-Connect/issues/5#issuecomment-98362192>.
>
Hi,

Restore didn't change anything. Same error exists after restore and
reconfigure (Twitter, Google).
I wonder if plugin requires more database permission than currently
configured: select, insert, update and delete table data + create and
drop tables. And if so what it would be?

**Comment by mistic100** [comment]
it requires ALTER indeed https://github.com/mistic100/Piwigo-Social-Connect/blob/master/maintain.class.php#L42

(If your MySQL user does not have rights to ALTER the tables, core updates of Piwigo will certainly fail too)

**Comment by WilbertSmith** [comment]
Thanks, that did the trick and now it works! It would be a worth of mention required database permissions in installation guide. If it's there I somehow managed to skip it ;).
Thanks for a quick resolution!
