### ISSUE TITLE
Trouble with LinkedIn OAuth

### ISSUE THREAD

**Issue by ewmalmbe** [mistic100/Piwigo-Social-Connect#6]
I've created my LinkedIn OAuth application in their developer console, added JavaScript valid domains and the full URLfor the Authorized Redirect as the plugin help so kindly provides:
{
http://myurl.com/plugins/oAuth/include/hybridauth/?hauth.done=LinkedIn
}

I've entered my key/secret and tried again and again to login. Piwigo Social Connect plugin LinkedIn option repeatedly says:
{
Error...

Authentication canceled
Close
}

Am I holding my mouth wrong or is this a LinkedIn App problem I've deleted the LinkedIn app and created a second app with the same failed result.

Thanks for your time.

**Comment by mistic100** [comment]
Can you grab files from https://github.com/hybridauth/hybridauth/tree/master/hybridauth/Hybrid and drop them in to `plugins\oAuth\include\hybridauth\Hybrid` ? and see if it solves the problem

**Comment by ewmalmbe** [comment]
Perfect, Mistic! After replacing the files in the Hybrid directory, LinkinIn OAuth works now, as well as FB and G+ (which worked before). 

Thanks for the quick response and solution. I really appreciate your help and your contributions to the project.

**Comment by mistic100** [comment]
keep it open until I fix, you are not alone

**Comment by mistic100** [comment]
f46cd3d9112955d78fba1f94ca6028600ed2841b
